### PR TITLE
Hosts page, main page and rudimentary block page.

### PR DESCRIPTION
**Pull request by agundy**
Not ready to be merged but basic implementation of explorer. Need to remove a lot of old code and still missing functionality but a rough draft of things to come.

### CODE REVIEW

**Comment by lukechampine** [comment]
wow, that's a lot of framework. I worry about our ability to maintain an angular project without a full-time JS dev. The block explorer doesn't seem complex or dynamic enough to warrant using a framework, but I suppose that may change. Maybe @mtlynch would like to weigh in here.

This seems like a good time to address something @DavidVorick suggested, which is to remove the Go code from the explorer entirely. Instead of having its own API, the explorer would call the `/blockexplorer/` routes of siae directly. This would require exposing those routes over the internet, and also configuring nginx (or equivalent) to serve the site instead of Go, but it might be worth the effort.

**Comment by DavidVorick** [comment]
I do want to make sure that pages and json is accessible from the website in a restful way similar to how other websites with an api do it.

**Comment by agundy** [comment]
Exposing the api endpoints may not be a bad idea. Though with how they are structured now there is no nice way to get some calls it seems like without doing a couple queries

**Comment by triazo** [comment]
the endpoints for the explorer are already exposed. exploreapi.siacoin.com. check out the nginx configs

**Comment by agundy** [comment]
I don't think I have access to that server. But you handle the Sia-Agent string?

**Comment by triazo** [comment]
its just an nginx foreward to the siad api. Siad does the agent checking. Its also on port 80

**Comment by agundy** [comment]
Looking to move to being just a frontend interface.

**Pull request closed without merging**
